/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 react_logo_circle.glb 
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-circle-540ff21ac0f54a038df6f634c7cce726
Title: React logo circle
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/react_logo_circle.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes['React-Logo_Material002_0'].geometry} material={materials['Material.002']} position={[0, 7.935, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[39.166, 39.166, 52.734]} />
          <mesh geometry={nodes.Backdrop_Material001_0.geometry} material={materials['Material.001']} position={[-17.091, 7.935, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[247.854, 247.854, 52.734]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/react_logo_circle.glb')
