/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot_shark.glb 
Author: Gianmarco (https://sketchfab.com/GianmArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-shark-2ec4e968688446878b23383769eca79f
Title: Robot Shark
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot_shark.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.053, 0, 0]}>
        <mesh geometry={nodes.Object_73.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_75.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_77.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_78.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_82.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_84.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_86.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.bolla} position={[-3.218, -0.401, -1.72]} rotation={[0.333, -0.132, -0.951]} scale={0.16} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.bolla} position={[-3.283, -0.682, -0.954]} rotation={[-0.709, -1.197, 2.156]} scale={0.197} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.bolla} position={[-3.177, -1.449, -1.16]} rotation={[2.768, -0.088, -2.363]} scale={0.12} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.bolla} position={[-3.256, -1.906, -0.456]} rotation={[-1.874, 1.185, -0.198]} scale={0.114} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.bolla} position={[-3.143, 4.325, -1.767]} rotation={[0, -Math.PI / 2, 0]} scale={0.136} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.bolla} position={[-3.062, 3.794, -1.537]} rotation={[0, -Math.PI / 2, 0]} scale={0.141} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.bolla} position={[-2.941, 2.733, -1.506]} rotation={[0, -Math.PI / 2, 0]} scale={0.15} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.bolla} position={[-2.76, 2.202, -1.12]} rotation={[0, -Math.PI / 2, 0]} scale={0.194} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.bolla} position={[-3.123, 1.672, -0.948]} rotation={[0, -Math.PI / 2, 0]} scale={0.137} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.bolla} position={[0.283, 5.393, -9.999]} rotation={[-2.053, 0.628, 2.649]} scale={0.154} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.bolla} position={[0.934, 5.477, -8.779]} rotation={[-1.799, -0.41, -1.589]} scale={0.187} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.bolla} position={[0.048, 4.514, -10.099]} rotation={[1.364, -0.044, -1.373]} scale={0.12} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.bolla} position={[0.58, 4.056, -8.593]} rotation={[1.015, 0.039, 2.503]} scale={0.133} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.bolla} position={[-0.193, 3.213, -8.199]} rotation={[1.054, -0.075, 2.07]} scale={0.158} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.bolla} position={[-0.076, 2.858, -7.934]} rotation={[-1.361, 0.822, -1.556]} scale={0.201} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.bolla} position={[0.655, 2.146, -8.476]} rotation={[0.92, -0.328, -1.42]} scale={0.125} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.bolla} position={[-0.518, 1.669, -7.831]} rotation={[-1.672, 0.008, -1.09]} scale={0.136} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.bolla} position={[-0.162, 10.09, -10.478]} rotation={[-1.31, -0.892, 1.422]} scale={0.162} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.bolla} position={[-0.306, 8.801, -11.012]} rotation={[-1.247, 1.058, -1.426]} scale={0.173} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.bolla} position={[0.762, 8.948, -9.393]} rotation={[2.596, 0.15, -1.728]} scale={0.11} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.bolla} position={[0.257, 8.196, -10.32]} rotation={[-1.034, -0.505, -0.647]} scale={0.115} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.bolla} position={[0.019, 6.842, -8.934]} rotation={[0.864, 1.157, 2.243]} scale={0.156} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.bolla} position={[-0.202, 6.436, -8.228]} rotation={[0.22, 0.344, -1.87]} scale={0.187} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.bolla} position={[0.107, 6.094, -7.971]} rotation={[-0.593, 0.859, -0.902]} scale={0.133} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.bolla} position={[-0.526, 5.503, -7.728]} rotation={[-1.235, 0.597, 2.641]} scale={0.122} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.bolla} position={[2.747, 4.325, -1.719]} rotation={[0, -Math.PI / 2, 0]} scale={0.135} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.bolla} position={[3.03, 3.794, -1.88]} rotation={[0, -Math.PI / 2, 0]} scale={0.125} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.bolla} position={[3.07, 2.733, -1.419]} rotation={[0, -Math.PI / 2, 0]} scale={0.152} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.bolla} position={[2.788, 2.202, -1.618]} rotation={[0, -Math.PI / 2, 0]} scale={0.174} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.bolla} position={[2.647, 1.672, -1.29]} rotation={[0, -Math.PI / 2, 0]} scale={0.126} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.bolla} position={[3.258, -0.401, -1.72]} rotation={[0.333, -0.132, -0.951]} scale={0.16} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.bolla} position={[3.194, -0.682, -0.954]} rotation={[-0.709, -1.197, 2.156]} scale={0.197} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.bolla} position={[3.299, -1.449, -1.16]} rotation={[2.768, -0.088, -2.363]} scale={0.12} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.bolla} position={[3.221, -1.906, -0.456]} rotation={[-1.874, 1.185, -0.198]} scale={0.114} />
    </group>
  )
}

useGLTF.preload('/robot_shark.glb')
